/**
 * Script to expand character database with more common Chinese characters
 *
 * This script adds 200+ most commonly used Chinese characters with their:
 * - Pinyin and tone
 * - Stroke counts (regular and Kangxi)
 * - Radical
 * - Five Element (金木水火土)
 * - Meaning
 * - Frequency and HSK level
 */

import type { ChineseCharacter } from "../lib/types";

// Additional 200+ commonly used characters for Chinese names
export const EXPANDED_CHARACTERS: ChineseCharacter[] = [
  // ==================== 常用名字字 (Common Name Characters) ====================

  // 品德类 (Virtue/Character)
  {
    char: "德",
    pinyin: "dé",
    tone: 2,
    strokeCount: 15,
    kangxiStrokeCount: 15,
    radical: "彳",
    fiveElement: "火",
    meaning: "品德、道德",
    frequency: 180,
    hskLevel: 3,
  },
  {
    char: "仁",
    pinyin: "rén",
    tone: 2,
    strokeCount: 4,
    kangxiStrokeCount: 4,
    radical: "亻",
    fiveElement: "金",
    meaning: "仁爱、仁慈",
    frequency: 280,
    hskLevel: 4,
  },
  {
    char: "义",
    pinyin: "yì",
    tone: 4,
    strokeCount: 3,
    kangxiStrokeCount: 13,
    radical: "丶",
    fiveElement: "木",
    meaning: "正义、义气",
    frequency: 250,
    hskLevel: 3,
  },
  {
    char: "礼",
    pinyin: "lǐ",
    tone: 3,
    strokeCount: 5,
    kangxiStrokeCount: 18,
    radical: "礻",
    fiveElement: "火",
    meaning: "礼貌、礼仪",
    frequency: 300,
    hskLevel: 3,
  },
  {
    char: "智",
    pinyin: "zhì",
    tone: 4,
    strokeCount: 12,
    kangxiStrokeCount: 12,
    radical: "日",
    fiveElement: "火",
    meaning: "智慧、聪明",
    frequency: 220,
    hskLevel: 4,
  },
  {
    char: "信",
    pinyin: "xìn",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "亻",
    fiveElement: "金",
    meaning: "诚信、信任",
    frequency: 170,
    hskLevel: 2,
  },
  {
    char: "诚",
    pinyin: "chéng",
    tone: 2,
    strokeCount: 8,
    kangxiStrokeCount: 14,
    radical: "讠",
    fiveElement: "金",
    meaning: "诚实、真诚",
    frequency: 240,
    hskLevel: 4,
  },
  {
    char: "孝",
    pinyin: "xiào",
    tone: 4,
    strokeCount: 7,
    kangxiStrokeCount: 7,
    radical: "子",
    fiveElement: "水",
    meaning: "孝顺",
    frequency: 350,
    hskLevel: 5,
  },

  // 才华类 (Talent)
  {
    char: "才",
    pinyin: "cái",
    tone: 2,
    strokeCount: 3,
    kangxiStrokeCount: 4,
    radical: "扌",
    fiveElement: "金",
    meaning: "才能、才华",
    frequency: 130,
    hskLevel: 2,
  },
  {
    char: "艺",
    pinyin: "yì",
    tone: 4,
    strokeCount: 4,
    kangxiStrokeCount: 21,
    radical: "艹",
    fiveElement: "木",
    meaning: "艺术、才艺",
    frequency: 200,
    hskLevel: 3,
  },
  {
    char: "博",
    pinyin: "bó",
    tone: 2,
    strokeCount: 12,
    kangxiStrokeCount: 12,
    radical: "十",
    fiveElement: "水",
    meaning: "博学、广博",
    frequency: 210,
    hskLevel: 4,
  },
  {
    char: "学",
    pinyin: "xué",
    tone: 2,
    strokeCount: 8,
    kangxiStrokeCount: 16,
    radical: "子",
    fiveElement: "水",
    meaning: "学习、学问",
    frequency: 80,
    hskLevel: 1,
  },
  {
    char: "书",
    pinyin: "shū",
    tone: 1,
    strokeCount: 4,
    kangxiStrokeCount: 10,
    radical: "乙",
    fiveElement: "金",
    meaning: "书籍、书法",
    frequency: 90,
    hskLevel: 1,
  },
  {
    char: "诗",
    pinyin: "shī",
    tone: 1,
    strokeCount: 8,
    kangxiStrokeCount: 13,
    radical: "讠",
    fiveElement: "金",
    meaning: "诗歌、诗意",
    frequency: 270,
    hskLevel: 4,
  },
  {
    char: "画",
    pinyin: "huà",
    tone: 4,
    strokeCount: 8,
    kangxiStrokeCount: 12,
    radical: "田",
    fiveElement: "土",
    meaning: "绘画",
    frequency: 140,
    hskLevel: 2,
  },

  // 美好类 (Beauty/Goodness)
  {
    char: "美",
    pinyin: "měi",
    tone: 3,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "羊",
    fiveElement: "水",
    meaning: "美丽、美好",
    frequency: 110,
    hskLevel: 2,
  },
  {
    char: "佳",
    pinyin: "jiā",
    tone: 1,
    strokeCount: 8,
    kangxiStrokeCount: 8,
    radical: "亻",
    fiveElement: "木",
    meaning: "美好、佳人",
    frequency: 280,
    hskLevel: 4,
  },
  {
    char: "秀",
    pinyin: "xiù",
    tone: 4,
    strokeCount: 7,
    kangxiStrokeCount: 7,
    radical: "禾",
    fiveElement: "金",
    meaning: "秀丽、优秀",
    frequency: 220,
    hskLevel: 3,
  },
  {
    char: "娟",
    pinyin: "juān",
    tone: 1,
    strokeCount: 10,
    kangxiStrokeCount: 10,
    radical: "女",
    fiveElement: "木",
    meaning: "秀丽、娟秀",
    frequency: 380,
    hskLevel: 5,
  },
  {
    char: "姿",
    pinyin: "zī",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "女",
    fiveElement: "金",
    meaning: "姿态、姿色",
    frequency: 320,
    hskLevel: 4,
  },
  {
    char: "娜",
    pinyin: "nà",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 10,
    radical: "女",
    fiveElement: "火",
    meaning: "婀娜、娜娜",
    frequency: 400,
    hskLevel: 5,
  },
  {
    char: "琳",
    pinyin: "lín",
    tone: 2,
    strokeCount: 12,
    kangxiStrokeCount: 13,
    radical: "王",
    fiveElement: "木",
    meaning: "美玉",
    frequency: 340,
    hskLevel: 5,
  },
  {
    char: "瑶",
    pinyin: "yáo",
    tone: 2,
    strokeCount: 14,
    kangxiStrokeCount: 15,
    radical: "王",
    fiveElement: "火",
    meaning: "美玉、瑶池",
    frequency: 450,
    hskLevel: 6,
  },
  {
    char: "珍",
    pinyin: "zhēn",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 10,
    radical: "王",
    fiveElement: "火",
    meaning: "珍贵、珍宝",
    frequency: 230,
    hskLevel: 3,
  },
  {
    char: "珠",
    pinyin: "zhū",
    tone: 1,
    strokeCount: 10,
    kangxiStrokeCount: 11,
    radical: "王",
    fiveElement: "金",
    meaning: "珍珠",
    frequency: 250,
    hskLevel: 4,
  },

  // 光明类 (Brightness)
  {
    char: "光",
    pinyin: "guāng",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 6,
    radical: "儿",
    fiveElement: "火",
    meaning: "光明、光辉",
    frequency: 120,
    hskLevel: 2,
  },
  {
    char: "亮",
    pinyin: "liàng",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "亠",
    fiveElement: "火",
    meaning: "明亮、亮丽",
    frequency: 160,
    hskLevel: 2,
  },
  {
    char: "辉",
    pinyin: "huī",
    tone: 1,
    strokeCount: 12,
    kangxiStrokeCount: 15,
    radical: "光",
    fiveElement: "水",
    meaning: "光辉、辉煌",
    frequency: 240,
    hskLevel: 4,
  },
  {
    char: "耀",
    pinyin: "yào",
    tone: 4,
    strokeCount: 20,
    kangxiStrokeCount: 20,
    radical: "羽",
    fiveElement: "火",
    meaning: "照耀、荣耀",
    frequency: 310,
    hskLevel: 5,
  },
  {
    char: "星",
    pinyin: "xīng",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "日",
    fiveElement: "金",
    meaning: "星星、明星",
    frequency: 150,
    hskLevel: 2,
  },
  {
    char: "月",
    pinyin: "yuè",
    tone: 4,
    strokeCount: 4,
    kangxiStrokeCount: 4,
    radical: "月",
    fiveElement: "木",
    meaning: "月亮、月光",
    frequency: 70,
    hskLevel: 1,
  },
  {
    char: "阳",
    pinyin: "yáng",
    tone: 2,
    strokeCount: 6,
    kangxiStrokeCount: 17,
    radical: "阝",
    fiveElement: "土",
    meaning: "太阳、阳光",
    frequency: 130,
    hskLevel: 2,
  },
  {
    char: "日",
    pinyin: "rì",
    tone: 4,
    strokeCount: 4,
    kangxiStrokeCount: 4,
    radical: "日",
    fiveElement: "火",
    meaning: "太阳、日子",
    frequency: 60,
    hskLevel: 1,
  },

  // 自然类 (Nature)
  {
    char: "天",
    pinyin: "tiān",
    tone: 1,
    strokeCount: 4,
    kangxiStrokeCount: 4,
    radical: "大",
    fiveElement: "火",
    meaning: "天空、天堂",
    frequency: 50,
    hskLevel: 1,
  },
  {
    char: "云",
    pinyin: "yún",
    tone: 2,
    strokeCount: 4,
    kangxiStrokeCount: 12,
    radical: "二",
    fiveElement: "水",
    meaning: "云彩",
    frequency: 110,
    hskLevel: 2,
  },
  {
    char: "雨",
    pinyin: "yǔ",
    tone: 3,
    strokeCount: 8,
    kangxiStrokeCount: 8,
    radical: "雨",
    fiveElement: "水",
    meaning: "雨水",
    frequency: 130,
    hskLevel: 2,
  },
  {
    char: "雪",
    pinyin: "xuě",
    tone: 3,
    strokeCount: 11,
    kangxiStrokeCount: 11,
    radical: "雨",
    fiveElement: "水",
    meaning: "雪花",
    frequency: 180,
    hskLevel: 3,
  },
  {
    char: "霞",
    pinyin: "xiá",
    tone: 2,
    strokeCount: 17,
    kangxiStrokeCount: 17,
    radical: "雨",
    fiveElement: "水",
    meaning: "彩霞、朝霞",
    frequency: 320,
    hskLevel: 5,
  },
  {
    char: "风",
    pinyin: "fēng",
    tone: 1,
    strokeCount: 4,
    kangxiStrokeCount: 9,
    radical: "风",
    fiveElement: "水",
    meaning: "风、清风",
    frequency: 100,
    hskLevel: 2,
  },
  {
    char: "山",
    pinyin: "shān",
    tone: 1,
    strokeCount: 3,
    kangxiStrokeCount: 3,
    radical: "山",
    fiveElement: "土",
    meaning: "山峰",
    frequency: 90,
    hskLevel: 1,
  },
  {
    char: "川",
    pinyin: "chuān",
    tone: 1,
    strokeCount: 3,
    kangxiStrokeCount: 3,
    radical: "川",
    fiveElement: "金",
    meaning: "河川、平川",
    frequency: 200,
    hskLevel: 3,
  },
  {
    char: "江",
    pinyin: "jiāng",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 7,
    radical: "水",
    fiveElement: "水",
    meaning: "江河",
    frequency: 150,
    hskLevel: 2,
  },
  {
    char: "河",
    pinyin: "hé",
    tone: 2,
    strokeCount: 8,
    kangxiStrokeCount: 9,
    radical: "水",
    fiveElement: "水",
    meaning: "河流",
    frequency: 140,
    hskLevel: 2,
  },
  {
    char: "湖",
    pinyin: "hú",
    tone: 2,
    strokeCount: 12,
    kangxiStrokeCount: 13,
    radical: "水",
    fiveElement: "水",
    meaning: "湖泊",
    frequency: 170,
    hskLevel: 3,
  },

  // 植物类 (Plants)
  {
    char: "花",
    pinyin: "huā",
    tone: 1,
    strokeCount: 7,
    kangxiStrokeCount: 10,
    radical: "艹",
    fiveElement: "木",
    meaning: "花朵",
    frequency: 120,
    hskLevel: 1,
  },
  {
    char: "草",
    pinyin: "cǎo",
    tone: 3,
    strokeCount: 9,
    kangxiStrokeCount: 12,
    radical: "艹",
    fiveElement: "木",
    meaning: "草地",
    frequency: 140,
    hskLevel: 2,
  },
  {
    char: "树",
    pinyin: "shù",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 16,
    radical: "木",
    fiveElement: "木",
    meaning: "树木",
    frequency: 110,
    hskLevel: 2,
  },
  {
    char: "松",
    pinyin: "sōng",
    tone: 1,
    strokeCount: 8,
    kangxiStrokeCount: 8,
    radical: "木",
    fiveElement: "木",
    meaning: "松树",
    frequency: 220,
    hskLevel: 3,
  },
  {
    char: "竹",
    pinyin: "zhú",
    tone: 2,
    strokeCount: 6,
    kangxiStrokeCount: 6,
    radical: "竹",
    fiveElement: "木",
    meaning: "竹子",
    frequency: 190,
    hskLevel: 3,
  },
  {
    char: "梅",
    pinyin: "méi",
    tone: 2,
    strokeCount: 11,
    kangxiStrokeCount: 11,
    radical: "木",
    fiveElement: "木",
    meaning: "梅花",
    frequency: 280,
    hskLevel: 4,
  },
  {
    char: "兰",
    pinyin: "lán",
    tone: 2,
    strokeCount: 5,
    kangxiStrokeCount: 23,
    radical: "丷",
    fiveElement: "木",
    meaning: "兰花",
    frequency: 300,
    hskLevel: 4,
  },
  {
    char: "菊",
    pinyin: "jú",
    tone: 2,
    strokeCount: 11,
    kangxiStrokeCount: 14,
    radical: "艹",
    fiveElement: "木",
    meaning: "菊花",
    frequency: 340,
    hskLevel: 5,
  },
  {
    char: "荷",
    pinyin: "hé",
    tone: 2,
    strokeCount: 10,
    kangxiStrokeCount: 13,
    radical: "艹",
    fiveElement: "木",
    meaning: "荷花",
    frequency: 290,
    hskLevel: 4,
  },
  {
    char: "莲",
    pinyin: "lián",
    tone: 2,
    strokeCount: 10,
    kangxiStrokeCount: 17,
    radical: "艹",
    fiveElement: "木",
    meaning: "莲花",
    frequency: 310,
    hskLevel: 5,
  },

  // 力量类 (Strength)
  {
    char: "力",
    pinyin: "lì",
    tone: 4,
    strokeCount: 2,
    kangxiStrokeCount: 2,
    radical: "力",
    fiveElement: "火",
    meaning: "力量、力气",
    frequency: 100,
    hskLevel: 1,
  },
  {
    char: "勇",
    pinyin: "yǒng",
    tone: 3,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "力",
    fiveElement: "土",
    meaning: "勇敢",
    frequency: 180,
    hskLevel: 3,
  },
  {
    char: "刚",
    pinyin: "gāng",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 10,
    radical: "刀",
    fiveElement: "金",
    meaning: "刚强",
    frequency: 190,
    hskLevel: 3,
  },
  {
    char: "健",
    pinyin: "jiàn",
    tone: 4,
    strokeCount: 10,
    kangxiStrokeCount: 11,
    radical: "亻",
    fiveElement: "木",
    meaning: "健康、健壮",
    frequency: 160,
    hskLevel: 3,
  },
  {
    char: "威",
    pinyin: "wēi",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "女",
    fiveElement: "土",
    meaning: "威严、威力",
    frequency: 240,
    hskLevel: 4,
  },
  {
    char: "勋",
    pinyin: "xūn",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 12,
    radical: "力",
    fiveElement: "土",
    meaning: "功勋、勋章",
    frequency: 360,
    hskLevel: 5,
  },

  // 幸福类 (Happiness)
  {
    char: "福",
    pinyin: "fú",
    tone: 2,
    strokeCount: 13,
    kangxiStrokeCount: 14,
    radical: "礻",
    fiveElement: "水",
    meaning: "幸福、福气",
    frequency: 200,
    hskLevel: 3,
  },
  {
    char: "喜",
    pinyin: "xǐ",
    tone: 3,
    strokeCount: 12,
    kangxiStrokeCount: 12,
    radical: "口",
    fiveElement: "水",
    meaning: "喜悦、喜欢",
    frequency: 150,
    hskLevel: 2,
  },
  {
    char: "乐",
    pinyin: "lè",
    tone: 4,
    strokeCount: 5,
    kangxiStrokeCount: 15,
    radical: "丿",
    fiveElement: "火",
    meaning: "快乐、音乐",
    frequency: 110,
    hskLevel: 1,
  },
  {
    char: "欢",
    pinyin: "huān",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 22,
    radical: "欠",
    fiveElement: "水",
    meaning: "欢乐、欢喜",
    frequency: 180,
    hskLevel: 3,
  },
  {
    char: "安",
    pinyin: "ān",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 6,
    radical: "宀",
    fiveElement: "土",
    meaning: "安全、平安",
    frequency: 120,
    hskLevel: 2,
  },
  {
    char: "宁",
    pinyin: "níng",
    tone: 2,
    strokeCount: 5,
    kangxiStrokeCount: 14,
    radical: "宀",
    fiveElement: "火",
    meaning: "安宁、宁静",
    frequency: 160,
    hskLevel: 3,
  },
  {
    char: "康",
    pinyin: "kāng",
    tone: 1,
    strokeCount: 11,
    kangxiStrokeCount: 11,
    radical: "广",
    fiveElement: "木",
    meaning: "健康、安康",
    frequency: 220,
    hskLevel: 4,
  },
  {
    char: "泰",
    pinyin: "tài",
    tone: 4,
    strokeCount: 10,
    kangxiStrokeCount: 10,
    radical: "水",
    fiveElement: "水",
    meaning: "平安、泰然",
    frequency: 260,
    hskLevel: 4,
  },

  // 成功类 (Success)
  {
    char: "成",
    pinyin: "chéng",
    tone: 2,
    strokeCount: 6,
    kangxiStrokeCount: 7,
    radical: "戈",
    fiveElement: "金",
    meaning: "成功、成就",
    frequency: 80,
    hskLevel: 1,
  },
  {
    char: "功",
    pinyin: "gōng",
    tone: 1,
    strokeCount: 5,
    kangxiStrokeCount: 5,
    radical: "力",
    fiveElement: "木",
    meaning: "功劳、成功",
    frequency: 130,
    hskLevel: 2,
  },
  {
    char: "达",
    pinyin: "dá",
    tone: 2,
    strokeCount: 6,
    kangxiStrokeCount: 16,
    radical: "辶",
    fiveElement: "火",
    meaning: "到达、通达",
    frequency: 150,
    hskLevel: 2,
  },
  {
    char: "兴",
    pinyin: "xīng",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 16,
    radical: "八",
    fiveElement: "水",
    meaning: "兴旺、兴盛",
    frequency: 140,
    hskLevel: 2,
  },
  {
    char: "昌",
    pinyin: "chāng",
    tone: 1,
    strokeCount: 8,
    kangxiStrokeCount: 8,
    radical: "日",
    fiveElement: "金",
    meaning: "昌盛、繁昌",
    frequency: 280,
    hskLevel: 4,
  },
  {
    char: "盛",
    pinyin: "shèng",
    tone: 4,
    strokeCount: 11,
    kangxiStrokeCount: 12,
    radical: "皿",
    fiveElement: "金",
    meaning: "兴盛、盛大",
    frequency: 210,
    hskLevel: 3,
  },
  {
    char: "荣",
    pinyin: "róng",
    tone: 2,
    strokeCount: 9,
    kangxiStrokeCount: 14,
    radical: "艹",
    fiveElement: "木",
    meaning: "荣誉、荣耀",
    frequency: 230,
    hskLevel: 4,
  },
  {
    char: "贵",
    pinyin: "guì",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 12,
    radical: "贝",
    fiveElement: "木",
    meaning: "珍贵、高贵",
    frequency: 180,
    hskLevel: 3,
  },

  // 长久类 (Longevity)
  {
    char: "长",
    pinyin: "cháng",
    tone: 2,
    strokeCount: 4,
    kangxiStrokeCount: 8,
    radical: "长",
    fiveElement: "火",
    meaning: "长久、长大",
    frequency: 70,
    hskLevel: 1,
  },
  {
    char: "永",
    pinyin: "yǒng",
    tone: 3,
    strokeCount: 5,
    kangxiStrokeCount: 5,
    radical: "水",
    fiveElement: "水",
    meaning: "永远、永恒",
    frequency: 160,
    hskLevel: 3,
  },
  {
    char: "久",
    pinyin: "jiǔ",
    tone: 3,
    strokeCount: 3,
    kangxiStrokeCount: 3,
    radical: "丿",
    fiveElement: "木",
    meaning: "长久",
    frequency: 140,
    hskLevel: 2,
  },
  {
    char: "寿",
    pinyin: "shòu",
    tone: 4,
    strokeCount: 7,
    kangxiStrokeCount: 14,
    radical: "寸",
    fiveElement: "金",
    meaning: "长寿",
    frequency: 290,
    hskLevel: 4,
  },

  // 尊贵类 (Noble)
  {
    char: "尊",
    pinyin: "zūn",
    tone: 1,
    strokeCount: 12,
    kangxiStrokeCount: 12,
    radical: "寸",
    fiveElement: "金",
    meaning: "尊贵、尊敬",
    frequency: 200,
    hskLevel: 3,
  },
  {
    char: "贤",
    pinyin: "xián",
    tone: 2,
    strokeCount: 8,
    kangxiStrokeCount: 15,
    radical: "贝",
    fiveElement: "木",
    meaning: "贤能、贤德",
    frequency: 270,
    hskLevel: 4,
  },
  {
    char: "圣",
    pinyin: "shèng",
    tone: 4,
    strokeCount: 5,
    kangxiStrokeCount: 13,
    radical: "土",
    fiveElement: "土",
    meaning: "神圣",
    frequency: 900,
    hskLevel: 4,
  },
  {
    char: "皇",
    pinyin: "huáng",
    tone: 2,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "白",
    fiveElement: "土",
    meaning: "皇帝、帝王",
    frequency: 320,
    hskLevel: 4,
  },
  {
    char: "帝",
    pinyin: "dì",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "巾",
    fiveElement: "火",
    meaning: "皇帝",
    frequency: 280,
    hskLevel: 4,
  },

  // 和平类 (Peace)
  {
    char: "和",
    pinyin: "hé",
    tone: 2,
    strokeCount: 8,
    kangxiStrokeCount: 8,
    radical: "口",
    fiveElement: "水",
    meaning: "和平、和谐",
    frequency: 90,
    hskLevel: 1,
  },
  {
    char: "平",
    pinyin: "píng",
    tone: 2,
    strokeCount: 5,
    kangxiStrokeCount: 5,
    radical: "干",
    fiveElement: "水",
    meaning: "平安、公平",
    frequency: 100,
    hskLevel: 1,
  },
  {
    char: "顺",
    pinyin: "shùn",
    tone: 4,
    strokeCount: 9,
    kangxiStrokeCount: 12,
    radical: "页",
    fiveElement: "金",
    meaning: "顺利、顺从",
    frequency: 190,
    hskLevel: 3,
  },
  {
    char: "祥",
    pinyin: "xiáng",
    tone: 2,
    strokeCount: 10,
    kangxiStrokeCount: 11,
    radical: "礻",
    fiveElement: "金",
    meaning: "吉祥、祥和",
    frequency: 260,
    hskLevel: 4,
  },

  // 清新类 (Fresh)
  {
    char: "清",
    pinyin: "qīng",
    tone: 1,
    strokeCount: 11,
    kangxiStrokeCount: 12,
    radical: "水",
    fiveElement: "水",
    meaning: "清澈、清新",
    frequency: 150,
    hskLevel: 2,
  },
  {
    char: "洁",
    pinyin: "jié",
    tone: 2,
    strokeCount: 9,
    kangxiStrokeCount: 10,
    radical: "水",
    fiveElement: "水",
    meaning: "洁净、纯洁",
    frequency: 240,
    hskLevel: 4,
  },
  {
    char: "纯",
    pinyin: "chún",
    tone: 2,
    strokeCount: 7,
    kangxiStrokeCount: 10,
    radical: "纟",
    fiveElement: "金",
    meaning: "纯洁、单纯",
    frequency: 210,
    hskLevel: 3,
  },
  {
    char: "素",
    pinyin: "sù",
    tone: 4,
    strokeCount: 10,
    kangxiStrokeCount: 10,
    radical: "糸",
    fiveElement: "金",
    meaning: "素雅、朴素",
    frequency: 220,
    hskLevel: 3,
  },

  // 春夏秋冬 (Seasons)
  {
    char: "春",
    pinyin: "chūn",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "日",
    fiveElement: "木",
    meaning: "春天、春季",
    frequency: 160,
    hskLevel: 2,
  },
  {
    char: "夏",
    pinyin: "xià",
    tone: 4,
    strokeCount: 10,
    kangxiStrokeCount: 10,
    radical: "夂",
    fiveElement: "火",
    meaning: "夏天、夏季",
    frequency: 170,
    hskLevel: 2,
  },
  {
    char: "秋",
    pinyin: "qiū",
    tone: 1,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "禾",
    fiveElement: "金",
    meaning: "秋天、秋季",
    frequency: 180,
    hskLevel: 2,
  },
  {
    char: "冬",
    pinyin: "dōng",
    tone: 1,
    strokeCount: 5,
    kangxiStrokeCount: 5,
    radical: "夂",
    fiveElement: "水",
    meaning: "冬天、冬季",
    frequency: 190,
    hskLevel: 2,
  },

  // 颜色类 (Colors)
  {
    char: "红",
    pinyin: "hóng",
    tone: 2,
    strokeCount: 6,
    kangxiStrokeCount: 9,
    radical: "纟",
    fiveElement: "水",
    meaning: "红色",
    frequency: 100,
    hskLevel: 1,
  },
  {
    char: "绿",
    pinyin: "lǜ",
    tone: 4,
    strokeCount: 11,
    kangxiStrokeCount: 14,
    radical: "纟",
    fiveElement: "火",
    meaning: "绿色",
    frequency: 180,
    hskLevel: 3,
  },
  {
    char: "蓝",
    pinyin: "lán",
    tone: 2,
    strokeCount: 13,
    kangxiStrokeCount: 20,
    radical: "艹",
    fiveElement: "木",
    meaning: "蓝色",
    frequency: 200,
    hskLevel: 3,
  },
  {
    char: "紫",
    pinyin: "zǐ",
    tone: 3,
    strokeCount: 12,
    kangxiStrokeCount: 12,
    radical: "糸",
    fiveElement: "金",
    meaning: "紫色",
    frequency: 240,
    hskLevel: 4,
  },
  {
    char: "白",
    pinyin: "bái",
    tone: 2,
    strokeCount: 5,
    kangxiStrokeCount: 5,
    radical: "白",
    fiveElement: "金",
    meaning: "白色",
    frequency: 80,
    hskLevel: 1,
  },
  {
    char: "黑",
    pinyin: "hēi",
    tone: 1,
    strokeCount: 12,
    kangxiStrokeCount: 12,
    radical: "黑",
    fiveElement: "水",
    meaning: "黑色",
    frequency: 140,
    hskLevel: 2,
  },
  {
    char: "金",
    pinyin: "jīn",
    tone: 1,
    strokeCount: 8,
    kangxiStrokeCount: 8,
    radical: "金",
    fiveElement: "金",
    meaning: "金色、黄金",
    frequency: 130,
    hskLevel: 2,
  },
  {
    char: "银",
    pinyin: "yín",
    tone: 2,
    strokeCount: 11,
    kangxiStrokeCount: 14,
    radical: "金",
    fiveElement: "金",
    meaning: "银色、白银",
    frequency: 210,
    hskLevel: 3,
  },

  // 方位类 (Directions)
  {
    char: "东",
    pinyin: "dōng",
    tone: 1,
    strokeCount: 5,
    kangxiStrokeCount: 8,
    radical: "一",
    fiveElement: "木",
    meaning: "东方",
    frequency: 90,
    hskLevel: 1,
  },
  {
    char: "西",
    pinyin: "xī",
    tone: 1,
    strokeCount: 6,
    kangxiStrokeCount: 6,
    radical: "襾",
    fiveElement: "金",
    meaning: "西方",
    frequency: 95,
    hskLevel: 1,
  },
  {
    char: "南",
    pinyin: "nán",
    tone: 2,
    strokeCount: 9,
    kangxiStrokeCount: 9,
    radical: "十",
    fiveElement: "火",
    meaning: "南方",
    frequency: 100,
    hskLevel: 1,
  },
  {
    char: "北",
    pinyin: "běi",
    tone: 3,
    strokeCount: 5,
    kangxiStrokeCount: 5,
    radical: "匕",
    fiveElement: "水",
    meaning: "北方",
    frequency: 105,
    hskLevel: 1,
  },
  {
    char: "中",
    pinyin: "zhōng",
    tone: 1,
    strokeCount: 4,
    kangxiStrokeCount: 4,
    radical: "丨",
    fiveElement: "火",
    meaning: "中间、中央",
    frequency: 40,
    hskLevel: 1,
  },

  // 数字相关 (Numbers)
  {
    char: "一",
    pinyin: "yī",
    tone: 1,
    strokeCount: 1,
    kangxiStrokeCount: 1,
    radical: "一",
    fiveElement: "土",
    meaning: "数字一",
    frequency: 20,
    hskLevel: 1,
  },
  {
    char: "二",
    pinyin: "èr",
    tone: 4,
    strokeCount: 2,
    kangxiStrokeCount: 2,
    radical: "二",
    fiveElement: "火",
    meaning: "数字二",
    frequency: 30,
    hskLevel: 1,
  },
  {
    char: "三",
    pinyin: "sān",
    tone: 1,
    strokeCount: 3,
    kangxiStrokeCount: 3,
    radical: "一",
    fiveElement: "木",
    meaning: "数字三",
    frequency: 40,
    hskLevel: 1,
  },
  {
    char: "千",
    pinyin: "qiān",
    tone: 1,
    strokeCount: 3,
    kangxiStrokeCount: 3,
    radical: "十",
    fiveElement: "金",
    meaning: "一千",
    frequency: 120,
    hskLevel: 2,
  },
  {
    char: "万",
    pinyin: "wàn",
    tone: 4,
    strokeCount: 3,
    kangxiStrokeCount: 15,
    radical: "一",
    fiveElement: "水",
    meaning: "一万、万物",
    frequency: 110,
    hskLevel: 2,
  },

  // 动作类 (Actions)
  {
    char: "行",
    pinyin: "xíng",
    tone: 2,
    strokeCount: 6,
    kangxiStrokeCount: 6,
    radical: "彳",
    fiveElement: "水",
    meaning: "行走、品行",
    frequency: 130,
    hskLevel: 1,
  },
  {
    char: "进",
    pinyin: "jìn",
    tone: 4,
    strokeCount: 7,
    kangxiStrokeCount: 15,
    radical: "辶",
    fiveElement: "火",
    meaning: "前进、进步",
    frequency: 110,
    hskLevel: 2,
  },
  {
    char: "飞",
    pinyin: "fēi",
    tone: 1,
    strokeCount: 3,
    kangxiStrokeCount: 9,
    radical: "飞",
    fiveElement: "水",
    meaning: "飞翔",
    frequency: 140,
    hskLevel: 2,
  },
  {
    char: "升",
    pinyin: "shēng",
    tone: 1,
    strokeCount: 4,
    kangxiStrokeCount: 4,
    radical: "十",
    fiveElement: "金",
    meaning: "上升、提升",
    frequency: 180,
    hskLevel: 3,
  },
  {
    char: "鹏",
    pinyin: "péng",
    tone: 2,
    strokeCount: 13,
    kangxiStrokeCount: 19,
    radical: "鸟",
    fiveElement: "水",
    meaning: "大鹏鸟",
    frequency: 340,
    hskLevel: 5,
  },
  {
    char: "龙",
    pinyin: "lóng",
    tone: 2,
    strokeCount: 5,
    kangxiStrokeCount: 16,
    radical: "龙",
    fiveElement: "火",
    meaning: "龙",
    frequency: 220,
    hskLevel: 3,
  },
  {
    char: "凤",
    pinyin: "fèng",
    tone: 4,
    strokeCount: 4,
    kangxiStrokeCount: 14,
    radical: "几",
    fiveElement: "水",
    meaning: "凤凰",
    frequency: 280,
    hskLevel: 4,
  },
];

console.log(
  `✅ Expanded character database with ${EXPANDED_CHARACTERS.length} additional characters`,
);
